#!/usr/bin/env python

"""
Campfire client

Usage: campfire-client <command> [<args>]

Written by Mathias Lafeldt <mathias.lafeldt@gmail.com>
"""

import sys, os
from campfire import *

def handle_cmd(campfire, args):
    cmd = args[1]
    if cmd == 'rooms':
        return campfire.rooms()
    elif cmd == 'user':
        return campfire.user(args[2])
    elif cmd == 'me':
        return campfire.me()
    elif cmd == 'presence':
        return campfire.presence()
    elif cmd == 'search':
        return campfire.search(args[2])
    else:
        room_id = os.environ['CAMPFIRE_ROOM']
        room = campfire.room(room_id)
        if cmd == 'show':
            return room.show()
        elif cmd == 'recent':
            return room.recent()
        elif cmd == 'transcript':
            return room.transcript()
        elif cmd == 'uploads':
            return room.uploads()
        elif cmd == 'join':
            return room.join()
        elif cmd == 'leave':
            return room.leave()
        elif cmd == 'lock':
            return room.lock()
        elif cmd == 'unlock':
            return room.unlock()
        elif cmd == 'speak':
            return room.speak(args[2])
        elif cmd == 'paste':
            return room.paste(args[2])
        elif cmd == 'play':
            return room.play(args[2])
        else:
            raise Exception('invalid command')


if __name__ == '__main__':
    token = os.environ['CAMPFIRE_TOKEN']
    url = os.environ['CAMPFIRE_URL']
    campfire = Campfire(url, token)
    print handle_cmd(campfire, sys.argv)
